basePath: /api
definitions:
  models.Barang:
    properties:
      id:
        type: string
      kategori_id:
        type: string
      nama:
        type: string
      stok:
        type: integer
      tanggal_buat:
        type: string
    type: object
  models.Kategori:
    properties:
      deskripsi:
        type: string
      id:
        type: string
      nama:
        type: string
      tanggal_buat:
        type: string
    type: object
  models.LoginRequest:
    properties:
      email:
        type: string
      password:
        type: string
    required:
    - email
    - password
    type: object
  models.Peminjaman:
    properties:
      barang_id:
        type: string
      email_peminjam:
        type: string
      id:
        type: string
      jumlah:
        type: integer
      nama_peminjam:
        type: string
      status:
        type: string
      tanggal_pinjam:
        type: string
      telepon_peminjam:
        type: string
    type: object
  models.RegisterRequest:
    properties:
      email:
        type: string
      password:
        minLength: 6
        type: string
      role:
        enum:
        - admin
        - user
        type: string
      username:
        maxLength: 50
        minLength: 3
        type: string
    required:
    - email
    - password
    - role
    - username
    type: object
host: beinventory-production.up.railway.app
info:
  contact:
    email: support@swagger.io
    name: API Support
    url: http://www.swagger.io/support
  description: API untuk sistem manajemen inventory dengan authentication JWT
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: Inventory Management API
  version: "1.0"
paths:
  /auth/login:
    post:
      consumes:
      - application/json
      description: Login dengan email dan password, return JWT token
      parameters:
      - description: Data login
        in: body
        name: login
        required: true
        schema:
          $ref: '#/definitions/models.LoginRequest'
      produces:
      - application/json
      responses:
        "200":
          description: Login berhasil
          schema:
            additionalProperties: true
            type: object
        "401":
          description: Unauthorized
          schema:
            additionalProperties: true
            type: object
        "500":
          description: Internal server error
          schema:
            additionalProperties: true
            type: object
      summary: Login user
      tags:
      - Authentication
  /auth/profile:
    get:
      description: Mendapatkan data profile user yang sedang login
      produces:
      - application/json
      responses:
        "200":
          description: Profile berhasil diambil
          schema:
            additionalProperties: true
            type: object
        "401":
          description: Unauthorized
          schema:
            additionalProperties: true
            type: object
        "404":
          description: User tidak ditemukan
          schema:
            additionalProperties: true
            type: object
      security:
      - BearerAuth: []
      summary: Get user profile
      tags:
      - Authentication
  /auth/register:
    post:
      consumes:
      - application/json
      description: Mendaftarkan user baru dengan username, email, password, dan role
      parameters:
      - description: Data user baru
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/models.RegisterRequest'
      produces:
      - application/json
      responses:
        "201":
          description: User berhasil didaftarkan
          schema:
            additionalProperties: true
            type: object
        "400":
          description: Bad request
          schema:
            additionalProperties: true
            type: object
        "500":
          description: Internal server error
          schema:
            additionalProperties: true
            type: object
      summary: Register user baru
      tags:
      - Authentication
  /barang:
    get:
      consumes:
      - application/json
      description: Mengambil semua data barang
      produces:
      - application/json
      responses:
        "200":
          description: List semua barang
          schema:
            items:
              $ref: '#/definitions/models.Barang'
            type: array
        "500":
          description: Internal server error
          schema:
            additionalProperties: true
            type: object
      security:
      - BearerAuth: []
      summary: Get all barang
      tags:
      - Barang
    post:
      consumes:
      - application/json
      description: Membuat data barang baru
      parameters:
      - description: Data barang baru
        in: body
        name: barang
        required: true
        schema:
          $ref: '#/definitions/models.Barang'
      produces:
      - application/json
      responses:
        "201":
          description: Barang berhasil dibuat
          schema:
            $ref: '#/definitions/models.Barang'
        "400":
          description: Bad request
          schema:
            additionalProperties: true
            type: object
        "500":
          description: Internal server error
          schema:
            additionalProperties: true
            type: object
      security:
      - BearerAuth: []
      summary: Create new barang
      tags:
      - Barang
  /barang/{id}:
    delete:
      consumes:
      - application/json
      description: Menghapus data barang berdasarkan ID
      parameters:
      - description: Barang ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Barang berhasil dihapus
          schema:
            additionalProperties: true
            type: object
        "400":
          description: ID tidak valid
          schema:
            additionalProperties: true
            type: object
        "500":
          description: Internal server error
          schema:
            additionalProperties: true
            type: object
      security:
      - BearerAuth: []
      summary: Delete barang
      tags:
      - Barang
    get:
      consumes:
      - application/json
      description: Mengambil data barang berdasarkan ID
      parameters:
      - description: Barang ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Data barang
          schema:
            $ref: '#/definitions/models.Barang'
        "400":
          description: ID tidak valid
          schema:
            additionalProperties: true
            type: object
        "404":
          description: Barang tidak ditemukan
          schema:
            additionalProperties: true
            type: object
      security:
      - BearerAuth: []
      summary: Get barang by ID
      tags:
      - Barang
    put:
      consumes:
      - application/json
      description: Mengupdate data barang berdasarkan ID
      parameters:
      - description: Barang ID
        in: path
        name: id
        required: true
        type: string
      - description: Data barang yang akan diupdate
        in: body
        name: barang
        required: true
        schema:
          $ref: '#/definitions/models.Barang'
      produces:
      - application/json
      responses:
        "200":
          description: Barang berhasil diupdate
          schema:
            additionalProperties: true
            type: object
        "400":
          description: Bad request
          schema:
            additionalProperties: true
            type: object
        "500":
          description: Internal server error
          schema:
            additionalProperties: true
            type: object
      security:
      - BearerAuth: []
      summary: Update barang
      tags:
      - Barang
  /kategori:
    get:
      consumes:
      - application/json
      description: Mengambil semua data kategori
      produces:
      - application/json
      responses:
        "200":
          description: List semua kategori
          schema:
            items:
              $ref: '#/definitions/models.Kategori'
            type: array
        "500":
          description: Internal server error
          schema:
            additionalProperties: true
            type: object
      security:
      - BearerAuth: []
      summary: Get all kategori
      tags:
      - Kategori
    post:
      consumes:
      - application/json
      description: Membuat data kategori baru
      parameters:
      - description: Data kategori baru
        in: body
        name: kategori
        required: true
        schema:
          $ref: '#/definitions/models.Kategori'
      produces:
      - application/json
      responses:
        "201":
          description: Kategori berhasil dibuat
          schema:
            $ref: '#/definitions/models.Kategori'
        "400":
          description: Bad request
          schema:
            additionalProperties: true
            type: object
        "500":
          description: Internal server error
          schema:
            additionalProperties: true
            type: object
      security:
      - BearerAuth: []
      summary: Create new kategori
      tags:
      - Kategori
  /kategori/{id}:
    delete:
      consumes:
      - application/json
      description: Menghapus data kategori berdasarkan ID
      parameters:
      - description: Kategori ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Kategori berhasil dihapus
          schema:
            additionalProperties: true
            type: object
        "400":
          description: ID tidak valid
          schema:
            additionalProperties: true
            type: object
        "500":
          description: Internal server error
          schema:
            additionalProperties: true
            type: object
      security:
      - BearerAuth: []
      summary: Delete kategori
      tags:
      - Kategori
    get:
      consumes:
      - application/json
      description: Mengambil data kategori berdasarkan ID
      parameters:
      - description: Kategori ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Data kategori
          schema:
            $ref: '#/definitions/models.Kategori'
        "400":
          description: ID tidak valid
          schema:
            additionalProperties: true
            type: object
        "404":
          description: Kategori tidak ditemukan
          schema:
            additionalProperties: true
            type: object
      security:
      - BearerAuth: []
      summary: Get kategori by ID
      tags:
      - Kategori
    put:
      consumes:
      - application/json
      description: Mengupdate data kategori berdasarkan ID
      parameters:
      - description: Kategori ID
        in: path
        name: id
        required: true
        type: string
      - description: Data kategori yang akan diupdate
        in: body
        name: kategori
        required: true
        schema:
          $ref: '#/definitions/models.Kategori'
      produces:
      - application/json
      responses:
        "200":
          description: Kategori berhasil diupdate
          schema:
            additionalProperties: true
            type: object
        "400":
          description: Bad request
          schema:
            additionalProperties: true
            type: object
        "500":
          description: Internal server error
          schema:
            additionalProperties: true
            type: object
      security:
      - BearerAuth: []
      summary: Update kategori
      tags:
      - Kategori
  /laporan/peminjaman:
    get:
      consumes:
      - application/json
      description: Mengambil laporan peminjaman dengan detail barang dan kategori
      produces:
      - application/json
      responses:
        "200":
          description: Laporan peminjaman lengkap
          schema:
            items:
              type: object
            type: array
        "500":
          description: Internal server error
          schema:
            additionalProperties: true
            type: object
      security:
      - BearerAuth: []
      summary: Get laporan peminjaman
      tags:
      - Laporan
  /peminjaman:
    get:
      consumes:
      - application/json
      description: Mengambil semua data peminjaman dengan opsi pencarian exact match
        nama peminjam
      parameters:
      - description: Pencarian exact match berdasarkan nama peminjam (case-insensitive)
        in: query
        name: search
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Daftar peminjaman
          schema:
            items:
              $ref: '#/definitions/models.Peminjaman'
            type: array
        "500":
          description: Terjadi kesalahan server
          schema:
            additionalProperties: true
            type: object
      security:
      - BearerAuth: []
      summary: Get all peminjaman
      tags:
      - Peminjaman
    post:
      consumes:
      - application/json
      description: Membuat data peminjaman baru
      parameters:
      - description: Data peminjaman baru
        in: body
        name: peminjaman
        required: true
        schema:
          $ref: '#/definitions/models.Peminjaman'
      produces:
      - application/json
      responses:
        "201":
          description: Peminjaman berhasil dibuat
          schema:
            $ref: '#/definitions/models.Peminjaman'
        "400":
          description: Bad request
          schema:
            additionalProperties: true
            type: object
        "404":
          description: Barang tidak ditemukan
          schema:
            additionalProperties: true
            type: object
        "500":
          description: Internal server error
          schema:
            additionalProperties: true
            type: object
      security:
      - BearerAuth: []
      summary: Create new peminjaman
      tags:
      - Peminjaman
  /peminjaman/{id}:
    delete:
      consumes:
      - application/json
      description: Menghapus data peminjaman berdasarkan ID
      parameters:
      - description: Peminjaman ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Data peminjaman berhasil dihapus
          schema:
            additionalProperties: true
            type: object
        "400":
          description: ID tidak valid
          schema:
            additionalProperties: true
            type: object
        "404":
          description: Data peminjaman tidak ditemukan
          schema:
            additionalProperties: true
            type: object
        "500":
          description: Internal server error
          schema:
            additionalProperties: true
            type: object
      security:
      - BearerAuth: []
      summary: Delete peminjaman
      tags:
      - Peminjaman
    get:
      consumes:
      - application/json
      description: Mengambil data peminjaman berdasarkan ID
      parameters:
      - description: Peminjaman ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Data peminjaman
          schema:
            $ref: '#/definitions/models.Peminjaman'
        "400":
          description: ID tidak valid
          schema:
            additionalProperties: true
            type: object
        "404":
          description: Data peminjaman tidak ditemukan
          schema:
            additionalProperties: true
            type: object
        "500":
          description: Internal server error
          schema:
            additionalProperties: true
            type: object
      security:
      - BearerAuth: []
      summary: Get peminjaman by ID
      tags:
      - Peminjaman
  /peminjaman/{id}/status:
    put:
      consumes:
      - application/json
      description: Mengupdate status peminjaman (dipinjam/dikembalikan)
      parameters:
      - description: Peminjaman ID
        in: path
        name: id
        required: true
        type: string
      - description: Status baru
        in: body
        name: status
        required: true
        schema:
          properties:
            status:
              type: string
          type: object
      produces:
      - application/json
      responses:
        "200":
          description: Status berhasil diperbarui
          schema:
            additionalProperties: true
            type: object
        "400":
          description: Bad request
          schema:
            additionalProperties: true
            type: object
        "404":
          description: Data tidak ditemukan
          schema:
            additionalProperties: true
            type: object
        "500":
          description: Internal server error
          schema:
            additionalProperties: true
            type: object
      security:
      - BearerAuth: []
      summary: Update status peminjaman
      tags:
      - Peminjaman
schemes:
- http
- https
securityDefinitions:
  BearerAuth:
    description: 'JWT token dengan format: Bearer {token}'
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
